
[general]
	remove_hypixel_lobby_join_and_mystery_box_messages = true
	legion_display = true
	combat_stats_display = true
	cooldown_display = true

[kuudra]
	kuudra_alerts = true
	supply_placement_waypoint = true
	number_of_runs_in_nametag = true

[bestiary]
	bestiary_tracker = true

	[bestiary.end]
		dragon_highlighter = true
		dragon_box = true

	[bestiary.spiders_den]
		broodmother = true
		rain_slimes = true
		arachnes_keeper = true

[levels]
	cheapest_skyblock_xp = true
	skyblock_xp_display = true
	skyblock_xp_decimal_in_nametag = true

[events]
	event_notifier = true
	auto_game_update_guild_message = true
	jacob_notifier = true
	auto_2x_powder_guild_message = true

