
[general]
	remove_hypixel_lobby_join_and_mystery_box_messages = true
	legion_display = true
	nodowntimealert = ""
	combat_stats_display = true
	no_downtime_alert = true
	cooldown_display = true
	show_downtime = true
	nosdowntimesalert = "test"
	healer_m7_ult_reminder = false
	show_speed_in_stat_tracker = true
	downtime = "test"
	stats_display = true

	[general.stats]
		show_farming_fortune = true
		show_crit_damage = true
		show_attack_speed = true
		show_crit_chance = true
		show_speed = true
		show_strength = true
		stats_display = true

[kuudra]
	percentages_and_waypoints_for_ballista_building = true
	stun_stopwatch = true
	kuudra_alerts = true
	supply_placement_waypoint = true
	kuudra_class = 0
	number_of_runs_in_nametag = true

[bestiary]
	bestiary_tracker = true

	[bestiary.end]
		dragon_highlighter = true
		dragon_box = true

	[bestiary.spiders_den]
		broodmother = true
		rain_slimes = true
		arachnes_keeper = true

[crimson_isle]
	percentages_and_waypoints_for_ballista_building = true
	kuudra_alerts = true
	hype_broken = true
	kuudra_class = 0
	supply_placement_waypoint = true

	[crimson_isle.kuudra]
		percentages_and_waypoints_for_ballista_building = true
		kuudra_alerts = true
		kuudra_class = 0
		supply_placement_waypoint = true

[levels]
	cheapest_skyblock_xp = true
	skyblock_xp_display = true
	skyblock_xp_decimal_in_nametag = true

[events]
	event_notifier = true
	auto_game_update_guild_message = true
	jacob_notifier = true
	auto_2x_powder_guild_message = true

